### PR TITLE
SSL_set_tlsext_host_name for Server Name Indication (SNI)

### PR DESCRIPTION
**Pull request by vshabanov**
Hi, I've added SSL function which is necessary for sites that require SNI (many CloudFlare sites at the moment).

Without setting host name SSL connections to these sites terminate with

    ProtocolError "error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error"

### CODE REVIEW

**Comment by vshabanov** [comment]
Hi @phonohawk,

Any news on this pull request?

Without it I can't upload new version of my own package to Hackage
https://github.com/bazqux/http-conduit-downloader

It would be really great if you could merge it and upload new HsOpenSSL version to Hackage.

**Comment by pavelkogan** [comment]
:+1:

**Comment by freizl** [comment]
+1

**Comment by singpolyma** [comment]
+1

**Comment by mstarzyk** [comment]
+1

**Comment by vshabanov** [comment]
I'm new maintainer of HsOpenSSL. https://github.com/vshabanov/HsOpenSSL is now the repo for HsOpenSSL. This pull request is not needed anymore. In future please send pull requests to the new repo.

**Pull request closed without merging**
